/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/moon/scene.gltf 
Author: Black Hole (https://sketchfab.com/blckhole)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-model-b9e1dfd765984d9b8f998bd4a6be97b5
Title: Sun Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
