/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/moon/scene.gltf 
Author: RenderX (https://sketchfab.com/RenderX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-26cc0b7878bb4d919b68e2be399db466
Title: moon
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere_Material001_0: THREE.Mesh
    Sphere_Material001_0_1: THREE.Mesh
    Sphere_Material001_0_2: THREE.Mesh
    Sphere_Material001_0_3: THREE.Mesh
    Sphere_Material001_0_4: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/moon/scene.gltf') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b964401c34154430bb1a8d7a5fa66a66fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sphere" rotation={[-1.264, 0.489, 0.961]} scale={100}>
                  <mesh name="Sphere_Material001_0" geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Sphere_Material001_0_1" geometry={nodes.Sphere_Material001_0_1.geometry} material={materials['Material.001']} />
                  <mesh name="Sphere_Material001_0_2" geometry={nodes.Sphere_Material001_0_2.geometry} material={materials['Material.001']} />
                  <mesh name="Sphere_Material001_0_3" geometry={nodes.Sphere_Material001_0_3.geometry} material={materials['Material.001']} />
                  <mesh name="Sphere_Material001_0_4" geometry={nodes.Sphere_Material001_0_4.geometry} material={materials['Material.001']} />
                </group>
                <group name="Camera" position={[528.602, 195.596, -369.365]} rotation={[3.125, -0.606, 2.837]} scale={100}>
                  <group name="Object_11" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/moon/scene.gltf')

export default Model
